# Generated by Django 3.2.14 on 2022-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentication_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukey', models.CharField(max_length=17)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
