# Generated by Django 3.2.14 on 2022-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S365_auth', '0002_alter_authentication_request_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukey', models.CharField(max_length=17)),
                ('token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
