# Generated by Django 3.2.14 on 2022-07-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=1024)),
                ('password', models.CharField(max_length=2048)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S365_auth.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Active_logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukey', models.CharField(max_length=1024)),
                ('token', models.CharField(max_length=1024)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S365_auth.client_accounts')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S365_auth.clients')),
            ],
        ),
    ]
