# Generated by Django 3.2.14 on 2022-07-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S365_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active_logins',
            options={'verbose_name': 'Active Login', 'verbose_name_plural': 'Active Logins'},
        ),
        migrations.AlterModelOptions(
            name='client_accounts',
            options={'verbose_name': 'Client Account', 'verbose_name_plural': 'Client Accounts'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.CreateModel(
            name='Failed_login_attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S365_auth.client_accounts')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S365_auth.clients')),
            ],
            options={
                'verbose_name': 'Failed Login Attempt',
                'verbose_name_plural': 'Failed Login Attempts',
            },
        ),
    ]
