# Generated by Django 3.2.14 on 2022-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S365_auth', '0004_two_factor_authentication_ukey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_factor_authentication',
            name='ukey',
            field=models.CharField(max_length=1024),
        ),
    ]
